@startuml UseCase_Karyawan
actor "Admin" as Admin
actor "Owner" as Owner
rectangle "Manajemen Karyawan" {
  usecase "Login" as UC_Login
  usecase "Tambah Karyawan" as UC_Tambah
  usecase "Edit Karyawan" as UC_Edit
  usecase "Hapus Karyawan" as UC_Hapus
  usecase "Lihat Daftar Karyawan" as UC_Lihat
}
Admin --> UC_Login
Admin --> UC_Tambah
Admin --> UC_Edit
Admin --> UC_Hapus
Admin --> UC_Lihat
Owner --> UC_Login
Owner --> UC_Tambah
Owner --> UC_Edit
Owner --> UC_Hapus
Owner --> UC_Lihat
@enduml